# This is a basic workflow to help you get started with Actions

name: Auto-update Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the auto-updater branch
  push:
    branches: [ auto-updater ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@auto-updater
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run electron:build --if-present
#       - run: npm test
      - run: npx semantic-release --branches auto-updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
