# This is a basic workflow to help you get started with Actions

name: Auto-update Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the auto-updater branch
  push:
    branches: [ auto-updater ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on. Ub
    # This means that the job will execute on a fresh virtual machine hosted by GitHub. 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "This is the secret token, but it will be sensored: "
          echo ${{ secrets.GITHUB_TOKEN }}
